# Generated by Django 5.1.6 on 2025-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_perro_perdido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='perdido',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='raza',
        ),
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_perdido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
