# Generated by Django 5.1.6 on 2025-03-25 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_perro_collar_perro_color_collar_perro_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='bordetella',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='cestodos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='cuadruple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='displasia_cadera',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='giardas_coccidios',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='giardia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='nematodos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='parvovirus_enfermo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='parvovirus_vacuna',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='pulgas',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='puppy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='quintuple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='rabia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='ruac',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='-', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='ruac_clave',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='sextuple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='tipo_pelo',
            field=models.CharField(blank=True, choices=[('corto', 'Corto'), ('rizado', 'Rizado'), ('duro', 'Duro'), ('lanoso_lanudo', 'lanoso/lanudo'), ('profundo', 'Profundo'), ('protector', 'Protector'), ('medio', 'Medio'), ('aspero', 'Aspero'), ('sedoso', 'Sedoso')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='ultima_alcaldia',
            field=models.CharField(choices=[('azcapotzalco', 'Azcapotzalco'), ('coyoacan', 'Coyoacan'), ('cuajimalpa', 'Cuajimalpa de Morelos'), ('gam', 'Gustavo A. Madero'), ('iztacalco', 'Iztacalco'), ('iztapalapa', 'Iztapalapa'), ('magdalena contreras', 'La Magdalena Contreras'), ('milpa alta', 'Milpa Alta'), ('alvaro obregon', 'Alvaro Obregon'), ('tlahuac', 'Tlahuac'), ('tlalpan', 'Tlalpan'), ('xochimilco', 'Xochimilco'), ('benito juarez', 'Benito Juarez'), ('cuauhtemoc', 'Cuauhtemoc'), ('miguel hidalgo', 'Miguel Hidalgo'), ('venustiano carranza', 'Venustiano Carranza')], default='-', max_length=29),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='ultima_calle',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='ultima_colonia',
            field=models.CharField(default='-', max_length=49),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='ultima_latitud',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='ultima_longitud',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro',
            name='color',
            field=models.CharField(choices=[('rojizo', 'Rojizo'), ('blanco', 'Blanco'), ('negro', 'Negro'), ('azul oscuro', 'Azul oscuro'), ('marron', 'Marron'), ('durazno', 'Durazno'), ('beige', 'Beige'), ('cafe', 'Cafe'), ('gris', 'Gris'), ('gris oscuro', 'Gris oscuro'), ('gris claro', 'Gris claro'), ('amarillo dorado', 'Amarillo dorado'), ('bicolor', 'Bicolor'), ('tricolor', 'Tricolor'), ('atigrado', 'Atrigrado'), ('arlequin', 'Arlequin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='color_collar',
            field=models.CharField(blank=True, choices=[('rojo', 'Rojo'), ('blanco', 'Blanco'), ('azul', 'Azul'), ('naranja', 'Naranja'), ('negro', 'Negro'), ('cielo', 'Azul Cielo'), ('gris', 'Gris'), ('rosa', 'Rosa'), ('morado', 'Morado')], max_length=25, null=True),
        ),
    ]
