# Generated by Django 5.1.6 on 2025-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0005_perro_bordetella_perro_cestodos_perro_cuadruple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='contactoAlbergue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('saludable', 'Saludable'), ('desnutrido', 'Desnutrido'), ('herido', 'Herido'), ('sucio', 'Sucio')], default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='identificador',
            field=models.CharField(choices=[('ruac', 'RUAC'), ('tatuaje', 'Tatuaje'), ('no', 'Ninguno')], default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='nombreAlbergue',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='tatuaje',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='ubicacionAlbergue',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
