# Generated by Django 5.1.6 on 2025-03-28 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0006_perro_contactoalbergue_perro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='bordetella',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='cestodos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='cuadruple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='displasia_cadera',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_perdido',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='giardas_coccidios',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='giardia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='identificador',
            field=models.CharField(blank=True, choices=[('ruac', 'RUAC'), ('tatuaje', 'Tatuaje'), ('no', 'Ninguno')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nematodos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='parvovirus_enfermo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='parvovirus_vacuna',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='pulgas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='puppy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='quintuple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='rabia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='sextuple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='ultima_alcaldia',
            field=models.CharField(blank=True, choices=[('azcapotzalco', 'Azcapotzalco'), ('coyoacan', 'Coyoacan'), ('cuajimalpa', 'Cuajimalpa de Morelos'), ('gam', 'Gustavo A. Madero'), ('iztacalco', 'Iztacalco'), ('iztapalapa', 'Iztapalapa'), ('magdalena contreras', 'La Magdalena Contreras'), ('milpa alta', 'Milpa Alta'), ('alvaro obregon', 'Alvaro Obregon'), ('tlahuac', 'Tlahuac'), ('tlalpan', 'Tlalpan'), ('xochimilco', 'Xochimilco'), ('benito juarez', 'Benito Juarez'), ('cuauhtemoc', 'Cuauhtemoc'), ('miguel hidalgo', 'Miguel Hidalgo'), ('venustiano carranza', 'Venustiano Carranza')], max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='ultima_colonia',
            field=models.CharField(blank=True, max_length=49, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='ultima_latitud',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='perro',
            name='ultima_longitud',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
